org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -Djava.util.logging.config.file=/dev/null -XX:+IgnoreUnrecognizedVMOptions --add-opens java.base/java.lang=ALL-UNNAMED -Dkotlin.version.detection.mode=skip
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.parallel=true
org.gradle.caching=false
kotlin.incremental=false
ksp.incremental=false
kotlin.jvm.target.validation.mode=warning
kotlin.jvm.toolchain.auto.detect=false
