org.gradle.jvmargs=-Xmx3584m -XX:MaxMetaspaceSize=1024m -Dkotlin.daemon.jvm.options=-Xmx2048m -Dfile.encoding=UTF-8 -Djava.util.logging.config.file=/dev/null --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.security=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --enable-preview -Dkotlin.version.detection.mode=skip --enable-native-access=ALL-UNNAMED
org.gradle.java.home=/opt/android-studio/jbr
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.caching=false
kotlin.incremental=false
ksp.incremental=false
kotlin.jvm.target.validation.mode=warning
kotlin.jvm.toolchain.auto.detect=false
kotlin.compiler.execution.strategy=daemon


