package com.pockethost.app.util

import android.content.Context
import androidx.compose.runtime.compositionLocalOf
import com.google.gson.Gson

class AppStrings(private val map: Map<String, String> = emptyMap()) {
    // Nav tabs
    val tabHome: String get() = map["tabHome"] ?: "Home"
    val tabPlayers: String get() = map["tabPlayers"] ?: "Players"
    val tabStorage: String get() = map["tabStorage"] ?: "Storage"
    val tabMods: String get() = map["tabMods"] ?: "Mods"
    val tabSettings: String get() = map["tabSettings"] ?: "Settings"
    // Server controls
    val startServer: String get() = map["startServer"] ?: "START SERVER"
    val stopServer: String get() = map["stopServer"] ?: "STOP"
    val restartServer: String get() = map["restartServer"] ?: "RESTART"
    val starting: String get() = map["starting"] ?: "STARTING..."
    val stopping: String get() = map["stopping"] ?: "STOPPING..."
    val restarting: String get() = map["restarting"] ?: "RESTARTING..."
    val offline: String get() = map["offline"] ?: "OFFLINE"
    val online: String get() = map["online"] ?: "ONLINE"
    // Server card
    val yourServer: String get() = map["yourServer"] ?: "YOUR SERVER"
    val hostedOn: String get() = map["hostedOn"] ?: "Hosted on PocketHost"
    val tapToSwap: String get() = map["tapToSwap"] ?: "One tap to swap your world or edit details"
    val stopToSwitch: String get() = map["stopToSwitch"] ?: "Stop the server to switch worlds"
    val tapToChangeVersion: String get() = map["tapToChangeVersion"] ?: "Tap to change version"
    val upgrade: String get() = map["upgrade"] ?: "UPGRADE"
    // RAM
    val ramAllocation: String get() = map["ramAllocation"] ?: "RAM Allocation"
    val ramLow: String get() = map["ramLow"] ?: "Low"
    val ramManual: String get() = map["ramManual"] ?: "Manual"
    val ramFull: String get() = map["ramFull"] ?: "Full"
    val ramHighPerf: String get() = map["ramHighPerf"] ?: "High-performance preset — may cause overheating"
    val ramLowPerf: String get() = map["ramLowPerf"] ?: "Low-performance preset — saves battery"
    val ramManualHint: String get() = map["ramManualHint"] ?: "Set a custom RAM allocation"
    // Console
    val console: String get() = map["console"] ?: "CONSOLE"
    val clearLog: String get() = map["clearLog"] ?: "Clear"
    val sendCommand: String get() = map["sendCommand"] ?: "Send command"
    // Players
    val players: String get() = map["players"] ?: "Players"
    val tabOnline: String get() = map["tabOnline"] ?: "Online"
    val tabAllPlayers: String get() = map["tabAllPlayers"] ?: "All Players"
    val tabWhitelist: String get() = map["tabWhitelist"] ?: "Whitelist"
    val tabOps: String get() = map["tabOps"] ?: "Ops"
    val tabBanned: String get() = map["tabBanned"] ?: "Banned"
    val kick: String get() = map["kick"] ?: "Kick"
    val ban: String get() = map["ban"] ?: "Ban"
    val makeOp: String get() = map["makeOp"] ?: "Make OP"
    val removeOp: String get() = map["removeOp"] ?: "Remove OP"
    val unban: String get() = map["unban"] ?: "Unban"
    val addPlayer: String get() = map["addPlayer"] ?: "Add Player"
    // Storage
    val worlds: String get() = map["worlds"] ?: "Worlds"
    val files: String get() = map["files"] ?: "Files"
    val share: String get() = map["share"] ?: "Share"
    val delete: String get() = map["delete"] ?: "Delete"
    val view: String get() = map["view"] ?: "View"
    val close: String get() = map["close"] ?: "Close"
    val releaseTrain26Title: String get() = map["releaseTrain26Title"] ?: "This version isn't stable yet"
    val releaseTrain26Body: String get() = map["releaseTrain26Body"] ?: "You're running game version %s. We're still improving 26.x in PocketHost — switch to 1.21.x for a better experience."
    val releaseTrain26Action: String get() = map["releaseTrain26Action"] ?: "Switch version"
    val folder: String get() = map["folder"] ?: "Folder"
    val uploading: String get() = map["uploading"] ?: "Uploading..."
    val chooseAction: String get() = map["chooseAction"] ?: "Choose an action"
    val unableToOpen: String get() = map["unableToOpen"] ?: "Unable to open file."
    // Settings sections
    val settingsServer: String get() = map["settingsServer"] ?: "Server"
    val settingsApp: String get() = map["settingsApp"] ?: "App"
    val settingsAccount: String get() = map["settingsAccount"] ?: "Account"
    val settingsAbout: String get() = map["settingsAbout"] ?: "About"
    val performance: String get() = map["performance"] ?: "PERFORMANCE & OPTIMIZATION"
    val worldSettings: String get() = map["worldSettings"] ?: "WORLD SETTINGS"
    val networking: String get() = map["networking"] ?: "NETWORKING"
    val appPreferences: String get() = map["appPreferences"] ?: "APP PREFERENCES"
    val sectionDeviceStorage: String get() = map["sectionDeviceStorage"] ?: "DEVICE STORAGE"
    val sectionAbout: String get() = map["sectionAbout"] ?: "ABOUT"
    // Settings labels
    val viewDistance: String get() = map["viewDistance"] ?: "View Distance"
    val viewDistanceDesc: String get() = map["viewDistanceDesc"] ?: "How far chunks are loaded"
    val viewDistanceHint: String get() = map["viewDistanceHint"] ?: "Lower values recommended for low-end devices"
    val simulationDistance: String get() = map["simulationDistance"] ?: "Simulation Distance"
    val simulationDistanceDesc: String get() = map["simulationDistanceDesc"] ?: "Tick distance for mobs/crops"
    val maxPowerMode: String get() = map["maxPowerMode"] ?: "Max Power Mode"
    val maxPowerModeDesc: String get() = map["maxPowerModeDesc"] ?: "Uses full RAM and max render distance. May cause overheating."
    val mobSpawning: String get() = map["mobSpawning"] ?: "Mob Spawning Optimization"
    val mobSpawningDesc: String get() = map["mobSpawningDesc"] ?: "Reduces entity count for better performance"
    val mobSpawningStandard: String get() = map["mobSpawningStandard"] ?: "Standard (Vanilla)"
    val difficulty: String get() = map["difficulty"] ?: "Difficulty"
    val gamemode: String get() = map["gamemode"] ?: "Gamemode"
    val whitelist: String get() = map["whitelist"] ?: "Whitelist"
    val maxPlayers: String get() = map["maxPlayers"] ?: "Max Players"
    val broadcastConsole: String get() = map["broadcastConsole"] ?: "Broadcast Console To Ops"
    val onlineMode: String get() = map["onlineMode"] ?: "Online Mode"
    val autoRestart: String get() = map["autoRestart"] ?: "Auto Restart"
    val autoRestartDesc: String get() = map["autoRestartDesc"] ?: "Restart server automatically on crash"
    val forceExternalJvm: String get() = map["forceExternalJvm"] ?: "Force External JVM"
    val forceExternalJvmDesc: String get() = map["forceExternalJvmDesc"] ?: "Use an external JVM instead of the bundled one"
    val configEditor: String get() = map["configEditor"] ?: "Advanced Config Editor"
    val configEditorDesc: String get() = map["configEditorDesc"] ?: "Edit server.properties directly"
    val openFolder: String get() = map["openFolder"] ?: "Open Server Folder"
    val openFolderDesc: String get() = map["openFolderDesc"] ?: "Browse server files in your file manager"
    val legalCenter: String get() = map["legalCenter"] ?: "Legal Center"
    val legalCenterDesc: String get() = map["legalCenterDesc"] ?: "Privacy Policy & Licenses"
    val unsavedChanges: String get() = map["unsavedChanges"] ?: "Unsaved Changes"
    val failedToSave: String get() = map["failedToSave"] ?: "Failed to Save"
    val retry: String get() = map["retry"] ?: "Retry"
    val save: String get() = map["save"] ?: "Save"
    val saving: String get() = map["saving"] ?: "Saving..."
    val saved: String get() = map["saved"] ?: "Saved"
    // Language
    val appLanguage: String get() = map["appLanguage"] ?: "App Language"
    val chooseLanguage: String get() = map["chooseLanguage"] ?: "Choose your preferred language"
    // Seed dialog
    val setWorldSeed: String get() = map["setWorldSeed"] ?: "Set World Seed"
    val worldSeedLabel: String get() = map["worldSeedLabel"] ?: "World Seed (optional)"
    // Mods / Plugins screen
    val downloaded: String get() = map["downloaded"] ?: "Downloaded"
    val managePluginsDesc: String get() = map["managePluginsDesc"] ?: "Manage installed plugins and resource packs"
    val add: String get() = map["add"] ?: "Add"
    val mods: String get() = map["mods"] ?: "Mods"
    val resourcePacks: String get() = map["resourcePacks"] ?: "Resource Packs"
    val noModsInstalled: String get() = map["noModsInstalled"] ?: "No mods installed yet"
    val noResourcePacksInstalled: String get() = map["noResourcePacksInstalled"] ?: "No resource packs installed yet"
    val useAddButton: String get() = map["useAddButton"] ?: "Use the Add button to import a file, or install one from the discover screen."
    val uploadFromDevice: String get() = map["uploadFromDevice"] ?: "Upload from device"
    val pasteUrl: String get() = map["pasteUrl"] ?: "Paste direct download URL"
    val download: String get() = map["download"] ?: "Download"
    val deleteConfirmDesc: String get() = map["deleteConfirmDesc"] ?: "This removes the file from the current server version."
    val enabled: String get() = map["enabled"] ?: "Enabled"
    val disabled: String get() = map["disabled"] ?: "Disabled"
    // PluginsSection component
    val addPlugin: String get() = map["addPlugin"] ?: "Add Plugin"
    val pluginsTip: String get() = map["pluginsTip"] ?: "Upload Bukkit/Spigot/Paper compatible .jar plugins. Find plugins at spigotmc.org or hangar.papermc.io"
    val noPluginsInstalled: String get() = map["noPluginsInstalled"] ?: "No plugins installed"
    val tapToAddPlugin: String get() = map["tapToAddPlugin"] ?: "Tap 'Add Plugin' to upload a .jar file"
    // Common
    val cancel: String get() = map["cancel"] ?: "Cancel"
    val accept: String get() = map["accept"] ?: "ACCEPT"
    val enable: String get() = map["enable"] ?: "Enable"
    val disable: String get() = map["disable"] ?: "Disable"
    val noInternetConnection: String get() = map["noInternetConnection"] ?: "No internet connection. Please check your network."
    // PluginsHubScreen
    val hubTabPlugins: String get() = map["hubTabPlugins"] ?: "Plugins"
    val hubTabMods: String get() = map["hubTabMods"] ?: "Mods"
    val hubTabResourcePacks: String get() = map["hubTabResourcePacks"] ?: "Resource Packs"
    val hubSearchPlaceholder: String get() = map["hubSearchPlaceholder"] ?: "Search online %s..."
    val hubModLoaderRequired: String get() = map["hubModLoaderRequired"] ?: "Mod loader required for mods"
    val hubModLoaderDesc: String get() = map["hubModLoaderDesc"] ?: "This server version is not using a supported mod loader. Switch this server to Fabric or Quilt to install mods."
    val hubAddingFile: String get() = map["hubAddingFile"] ?: "Adding file: %d%%"
    val hubDownloading: String get() = map["hubDownloading"] ?: "Downloading: %d%%"
    val hubSectionDownloaded: String get() = map["hubSectionDownloaded"] ?: "Downloaded"
    val hubSectionDownloadedDesc: String get() = map["hubSectionDownloadedDesc"] ?: "Manage what is already stored for this server version."
    val hubSectionDiscover: String get() = map["hubSectionDiscover"] ?: "Discover Online"
    val hubSectionDiscoverDesc: String get() = map["hubSectionDiscoverDesc"] ?: "Only online results are shown here. Installed matches are marked for you."
    val hubTapToExpand: String get() = map["hubTapToExpand"] ?: "Tap arrow to expand"
    val hubNoDownloaded: String get() = map["hubNoDownloaded"] ?: "No downloaded %s yet for this version."
    val hubNoOnlineResults: String get() = map["hubNoOnlineResults"] ?: "No online %s matched this search."
    val hubLoadingOnline: String get() = map["hubLoadingOnline"] ?: "Loading online results..."
    val hubRetry: String get() = map["hubRetry"] ?: "Retry"
    val hubAdd: String get() = map["hubAdd"] ?: "Add"
    val hubInstall: String get() = map["hubInstall"] ?: "Install"
    val hubInstalling: String get() = map["hubInstalling"] ?: "Installing..."
    val hubInstalled: String get() = map["hubInstalled"] ?: "Installed"
    val hubSupportedMod: String get() = map["hubSupportedMod"] ?: "Supported Mod"
    val hubUnsupported: String get() = map["hubUnsupported"] ?: "Unsupported"
    val hubUploadFromDevice: String get() = map["hubUploadFromDevice"] ?: "Upload from device"
    val hubPasteUrl: String get() = map["hubPasteUrl"] ?: "Paste direct download URL"
    val hubDownloadAction: String get() = map["hubDownloadAction"] ?: "Download"
    val hubDeleteTitle: String get() = map["hubDeleteTitle"] ?: "Delete %s?"
    val hubDeleteDesc: String get() = map["hubDeleteDesc"] ?: "This will permanently remove the file from this server version."
    val hubDeleteAction: String get() = map["hubDeleteAction"] ?: "Delete"
    val hubSearchRetry: String get() = map["hubSearchRetry"] ?: "Searches are cached and rate-limited, so retrying in a moment usually works."
    val hubDetailFile: String get() = map["hubDetailFile"] ?: "File"
    val hubDetailVersion: String get() = map["hubDetailVersion"] ?: "Version"
    val hubDetailSize: String get() = map["hubDetailSize"] ?: "Size"
    val hubDetailApply: String get() = map["hubDetailApply"] ?: "Apply"
    val hubDetailApplyDesc: String get() = map["hubDetailApplyDesc"] ?: "Restart the server after changing plugins or packs."
    val hubDetailVersionNotProvided: String get() = map["hubDetailVersionNotProvided"] ?: "Not provided"
    val hubDetailDownloads: String get() = map["hubDetailDownloads"] ?: "Downloads"
    val hubDetailSource: String get() = map["hubDetailSource"] ?: "Source"
    val hubDetailSlug: String get() = map["hubDetailSlug"] ?: "Slug"
    val hubDetailDescription: String get() = map["hubDetailDescription"] ?: "Description"
    val hubDetailSupport: String get() = map["hubDetailSupport"] ?: "Support"
    val hubCommunityListing: String get() = map["hubCommunityListing"] ?: "Community listing"
    val hubEnabledStatus: String get() = map["hubEnabledStatus"] ?: "Enabled"
    val hubDisabledStatus: String get() = map["hubDisabledStatus"] ?: "Disabled"
    // WorldsScreen
    val worldsSectionCurrentWorld: String get() = map["worldsSectionCurrentWorld"] ?: "CURRENT WORLD"
    val worldsMbOnDisk: String get() = map["worldsMbOnDisk"] ?: "%s MB on disk"
    val worldsBackingUp: String get() = map["worldsBackingUp"] ?: "BACKING UP..."
    val worldsBackup: String get() = map["worldsBackup"] ?: "BACKUP"
    val worldsReset: String get() = map["worldsReset"] ?: "RESET"
    val worldsStopBeforeReset: String get() = map["worldsStopBeforeReset"] ?: "Stop the server before resetting the world."
    val worldsSectionSlots: String get() = map["worldsSectionSlots"] ?: "WORLD SLOTS"
    val worldsAdd: String get() = map["worldsAdd"] ?: "ADD"
    val worldsSlotHint: String get() = map["worldsSlotHint"] ?: "Slide left to delete. Active worlds can only be deleted when the server is stopped."
    val worldsSectionImport: String get() = map["worldsSectionImport"] ?: "IMPORT DIMENSIONS"
    val worldsImportGuideTitle: String get() = map["worldsImportGuideTitle"] ?: "Import guide"
    val worldsImportGuideDesc: String get() = map["worldsImportGuideDesc"] ?: "Tap to see how world and dimension imports work."
    val worldsUploadOverworld: String get() = map["worldsUploadOverworld"] ?: "Upload Overworld"
    val worldsUploadNether: String get() = map["worldsUploadNether"] ?: "Upload Nether"
    val worldsUploadEnd: String get() = map["worldsUploadEnd"] ?: "Upload The End"
    val worldsOverworldSub: String get() = map["worldsOverworldSub"] ?: "Main world (%s)"
    val worldsNetherSub: String get() = map["worldsNetherSub"] ?: "Nether dimension (%s_nether)"
    val worldsEndSub: String get() = map["worldsEndSub"] ?: "End dimension (%s_the_end)"
    val worldsSectionBackupHistory: String get() = map["worldsSectionBackupHistory"] ?: "BACKUP HISTORY"
    val worldsFiles: String get() = map["worldsFiles"] ?: "%d files"
    val worldsNoBackups: String get() = map["worldsNoBackups"] ?: "No backups found"
    val worldsStopToSwitch: String get() = map["worldsStopToSwitch"] ?: "Stop server to switch worlds"
    val worldsStopToUpload: String get() = map["worldsStopToUpload"] ?: "Stop server to upload"
    val worldsExtracted: String get() = map["worldsExtracted"] ?: "%d%% extracted"
    val worldsUpload: String get() = map["worldsUpload"] ?: "UPLOAD"
    val worldsActive: String get() = map["worldsActive"] ?: "ACTIVE"
    val worldsDelete: String get() = map["worldsDelete"] ?: "Delete"
    // Reset dialog
    val worldsResetTitle: String get() = map["worldsResetTitle"] ?: "Reset World"
    val worldsResetDesc: String get() = map["worldsResetDesc"] ?: "Choose what to delete. Plugins, mods, config files, and server.properties will be preserved."
    val worldsResetRowWorld: String get() = map["worldsResetRowWorld"] ?: "World folders (world, world_nether, world_the_end)"
    val worldsResetRowPlayers: String get() = map["worldsResetRowPlayers"] ?: "Player data (playerdata, stats, advancements)"
    val worldsResetRowDatapacks: String get() = map["worldsResetRowDatapacks"] ?: "Datapacks"
    val worldsResetRowLogs: String get() = map["worldsResetRowLogs"] ?: "Logs"
    val worldsResetPreserved: String get() = map["worldsResetPreserved"] ?: "Always preserved: plugins/, mods/, config/, server.properties, and config files."
    val worldsResetDeleteSelected: String get() = map["worldsResetDeleteSelected"] ?: "DELETE SELECTED"
    val worldsCancel: String get() = map["worldsCancel"] ?: "CANCEL"
    // Restore dialog
    val worldsRestoreTitle: String get() = map["worldsRestoreTitle"] ?: "Restore Backup?"
    val worldsRestoreDesc: String get() = map["worldsRestoreDesc"] ?: "This will restore:\n- Worlds and dimension data\n- Plugins, mods, and resource packs\n- Server configs and settings\n\nYour current server files will be overwritten.\nMake sure the server is stopped before restoring."
    val worldsRestoreAction: String get() = map["worldsRestoreAction"] ?: "RESTORE"
    // Delete backup dialog
    val worldsDeleteBackupTitle: String get() = map["worldsDeleteBackupTitle"] ?: "Delete Backup?"
    val worldsDeleteBackupDesc: String get() = map["worldsDeleteBackupDesc"] ?: "Are you sure you want to delete %s?"
    val worldsDeleteAction: String get() = map["worldsDeleteAction"] ?: "DELETE"
    // Delete world dialog
    val worldsDeleteWorldTitle: String get() = map["worldsDeleteWorldTitle"] ?: "Delete World?"
    val worldsDeleteWorldActive: String get() = map["worldsDeleteWorldActive"] ?: "Delete %s? PocketHost will switch to another saved world first."
    val worldsDeleteWorldInactive: String get() = map["worldsDeleteWorldInactive"] ?: "Delete %s? This removes the world from storage."
    // Import guide dialog
    val worldsImportGuideSheetTitle: String get() = map["worldsImportGuideSheetTitle"] ?: "Import Guide"
    val worldsImportGuideText1: String get() = map["worldsImportGuideText1"] ?: "Aternos exports can be uploaded as 3 separate ZIPs: Overworld, Nether, and The End."
    val worldsImportGuideText2: String get() = map["worldsImportGuideText2"] ?: "Most other world backups already include all dimensions in one archive, so a single world backup import is enough."
    val worldsImportGuideClose: String get() = map["worldsImportGuideClose"] ?: "CLOSE"
    // FilesScreen
    val filesSectionCurrentWorld: String get() = map["filesSectionCurrentWorld"] ?: "CURRENT WORLD"
    val filesActiveFolder: String get() = map["filesActiveFolder"] ?: "Active folder • %sMB"
    val filesDeleteActiveWorld: String get() = map["filesDeleteActiveWorld"] ?: "DELETE ACTIVE WORLD"
    val filesAddAnotherWorld: String get() = map["filesAddAnotherWorld"] ?: "Add another world before deleting this one."
    val filesSectionSeed: String get() = map["filesSectionSeed"] ?: "WORLD SEED"
    val filesSeedRandom: String get() = map["filesSeedRandom"] ?: "Random"
    val filesSeedUsedFor: String get() = map["filesSeedUsedFor"] ?: "Seed used for generation"
    val filesSeedCopied: String get() = map["filesSeedCopied"] ?: "Seed copied to clipboard."
    val filesSeedEdit: String get() = map["filesSeedEdit"] ?: "EDIT"
    val filesSectionCore: String get() = map["filesSectionCore"] ?: "SERVER CORE"
    val filesMinecraftJava: String get() = map["filesMinecraftJava"] ?: "Java Edition %s"
    val filesSwitchOrUpgrade: String get() = map["filesSwitchOrUpgrade"] ?: "Switch or upgrade"
    val filesChange: String get() = map["filesChange"] ?: "CHANGE"
    val filesSectionBackup: String get() = map["filesSectionBackup"] ?: "BACKUP & MAINTENANCE"
    val filesQuickBackup: String get() = map["filesQuickBackup"] ?: "Quick Backup"
    val filesGoogleCloudBackup: String get() = map["filesGoogleCloudBackup"] ?: "Google Cloud Backup"
    val filesUploadToGoogleCloud: String get() = map["filesUploadToGoogleCloud"] ?: "UPLOAD TO GOOGLE CLOUD"
    val filesGoogleCloudBackupDesc: String get() = map["filesGoogleCloudBackupDesc"] ?: "Upload active world backup to Google Drive cloud storage."
    val filesConnectGooglePrompt: String get() = map["filesConnectGooglePrompt"] ?: "Connect Google account to enable Google Cloud backup."
    val filesAdvanced: String get() = map["filesAdvanced"] ?: "Advanced..."
    val filesSeedDialogTitle: String get() = map["filesSeedDialogTitle"] ?: "Set World Seed"
    val filesSeedDialogDesc: String get() = map["filesSeedDialogDesc"] ?: "Enter a seed for your world. Leave it empty for a random world."
    val filesSeedDialogLabel: String get() = map["filesSeedDialogLabel"] ?: "World Seed (optional)"
    val filesSeedDialogConfirm: String get() = map["filesSeedDialogConfirm"] ?: "CONFIRM"
    val filesSeedDialogCancel: String get() = map["filesSeedDialogCancel"] ?: "CANCEL"
    val filesDeleteWorldTitle: String get() = map["filesDeleteWorldTitle"] ?: "Delete Active World?"
    val filesDeleteWorldDesc: String get() = map["filesDeleteWorldDesc"] ?: "This will permanently delete %s and switch to another saved world if one exists."
    val filesDeleteAction: String get() = map["filesDeleteAction"] ?: "DELETE"
    val filesDeleteCancel: String get() = map["filesDeleteCancel"] ?: "CANCEL"

    // Onboarding strings
    val onboardingStepWelcome: String get() = map["onboardingStepWelcome"] ?: "WELCOME"
    val onboardingStepHowItWorks: String get() = map["onboardingStepHowItWorks"] ?: "HOW IT WORKS"
    val onboardingStepBringYourWorld: String get() = map["onboardingStepBringYourWorld"] ?: "BRING YOUR WORLD"
    val onboardingStepFullControl: String get() = map["onboardingStepFullControl"] ?: "FULL CONTROL"
    val onboardingStepCrossPlay: String get() = map["onboardingStepCrossPlay"] ?: "CROSS-PLAY READY"
    val onboardingStepPickRegion: String get() = map["onboardingStepPickRegion"] ?: "PICK REGION"
    val onboardingStepPermissions: String get() = map["onboardingStepPermissions"] ?: "PERMISSIONS"
    val onboardingStepGoogleSignIn: String get() = map["onboardingStepGoogleSignIn"] ?: "GOOGLE SIGN-IN"
    val onboardingStepSetup: String get() = map["onboardingStepSetup"] ?: "SETUP"
    val onboardingStepReady: String get() = map["onboardingStepReady"] ?: "ALL SET"
    val onboardingReadyTitle: String get() = map["onboardingReadyTitle"] ?: "Welcome to PocketHost"
    val onboardingReadySubtitle: String get() = map["onboardingReadySubtitle"] ?: "Your phone is ready to host. Here is what comes next."
    val onboardingReadyCreateTitle: String get() = map["onboardingReadyCreateTitle"] ?: "Create your first server"
    val onboardingReadyCreateBody: String get() = map["onboardingReadyCreateBody"] ?: "Pick a name, a server type and a Minecraft version."
    val onboardingReadyStartTitle: String get() = map["onboardingReadyStartTitle"] ?: "Press Start"
    val onboardingReadyStartBody: String get() = map["onboardingReadyStartBody"] ?: "PocketHost downloads what it needs and boots the server."
    val onboardingReadyInviteTitle: String get() = map["onboardingReadyInviteTitle"] ?: "Invite your friends"
    val onboardingReadyInviteBody: String get() = map["onboardingReadyInviteBody"] ?: "Share the address and play together, on Wi-Fi or over the internet."
    val onboardingWelcomeTitle: String get() = map["onboardingWelcomeTitle"] ?: "Your phone is now\na dedicated game server"
    val onboardingWelcomeSubtitle: String get() = map["onboardingWelcomeSubtitle"] ?: "Host Java Edition servers for free.\nNo PC required. Play with anyone."
    val onboardingFreeToHost: String get() = map["onboardingFreeToHost"] ?: "Free to host"
    val onboardingNoPcNeeded: String get() = map["onboardingNoPcNeeded"] ?: "No PC needed"
    val onboardingInviteAnyone: String get() = map["onboardingInviteAnyone"] ?: "Invite anyone"
    val onboardingAgreeTermsPolicy: String get() = map["onboardingAgreeTermsPolicy"] ?: "I agree to the terms & policy"
    val onboardingPrivacyPolicy: String get() = map["onboardingPrivacyPolicy"] ?: "Privacy Policy"
    val onboardingTermsOfUse: String get() = map["onboardingTermsOfUse"] ?: "Terms of Use"
    val onboardingHowItWorksTitle: String get() = map["onboardingHowItWorksTitle"] ?: "How it works"
    val onboardingStep1Title: String get() = map["onboardingStep1Title"] ?: "1. Start your server"
    val onboardingStep1Body: String get() = map["onboardingStep1Body"] ?: "Paper runs locally on your phone and uses the memory you already have."
    val onboardingStep2Title: String get() = map["onboardingStep2Title"] ?: "2. Share your address"
    val onboardingStep2Body: String get() = map["onboardingStep2Body"] ?: "PocketHost gives you a unique relay address that friends can connect to."
    val onboardingStep3Title: String get() = map["onboardingStep3Title"] ?: "3. Friends join instantly"
    val onboardingStep3Body: String get() = map["onboardingStep3Body"] ?: "Java Edition players connect straight through the relay with minimal friction."
    val onboardingImportTitle: String get() = map["onboardingImportTitle"] ?: "Moving from Aternos or Minehut?"
    val onboardingImportSubtitle: String get() = map["onboardingImportSubtitle"] ?: "Bring your world, plugins, and config with you. No starting over."
    val onboardingImportWorldTitle: String get() = map["onboardingImportWorldTitle"] ?: "Upload world zip"
    val onboardingImportWorldBody: String get() = map["onboardingImportWorldBody"] ?: "Export from Aternos, drop the archive in PocketHost, and keep going."
    val onboardingImportPluginsTitle: String get() = map["onboardingImportPluginsTitle"] ?: "Keep your plugins"
    val onboardingImportPluginsBody: String get() = map["onboardingImportPluginsBody"] ?: "Reuse the same .jar files. Your plugin stack moves with you."
    val onboardingImportConfigTitle: String get() = map["onboardingImportConfigTitle"] ?: "Config & ops carry over"
    val onboardingImportConfigBody: String get() = map["onboardingImportConfigBody"] ?: "server.properties, whitelist, and operator access remain intact."
    val onboardingFeaturesTitle: String get() = map["onboardingFeaturesTitle"] ?: "Full control, right in your pocket"
    val onboardingFeaturesSubtitle: String get() = map["onboardingFeaturesSubtitle"] ?: "Not a stripped-down app. This is the real server toolkit."
    val onboardingFeaturesBanner: String get() = map["onboardingFeaturesBanner"] ?: "Everything you need in one place"
    val onboardingFeaturesPluginsBody: String get() = map["onboardingFeaturesPluginsBody"] ?: "Install compatible plugins"
    val onboardingFeaturesConsoleTitle: String get() = map["onboardingFeaturesConsoleTitle"] ?: "Live console"
    val onboardingFeaturesConsoleBody: String get() = map["onboardingFeaturesConsoleBody"] ?: "Run commands and watch logs"
    val onboardingFeaturesPlayersBody: String get() = map["onboardingFeaturesPlayersBody"] ?: "Manage players"
    val onboardingFeaturesConfigTitle: String get() = map["onboardingFeaturesConfigTitle"] ?: "properties"
    val onboardingFeaturesConfigBody: String get() = map["onboardingFeaturesConfigBody"] ?: "Edit settings directly"
    val onboardingCrossPlayTitle: String get() = map["onboardingCrossPlayTitle"] ?: "Cross-play is supported"
    val onboardingCrossPlaySubtitle: String get() = map["onboardingCrossPlaySubtitle"] ?: "PocketHost supports Java and Bedrock cross-play when the bridge is enabled in your server setup."
    val onboardingCrossPlayJavaBedrock: String get() = map["onboardingCrossPlayJavaBedrock"] ?: "Java + Bedrock"
    val onboardingCrossPlayJavaBedrockBody: String get() = map["onboardingCrossPlayJavaBedrockBody"] ?: "Friends on PC and mobile can join the same world together through the relay."
    val onboardingCrossPlayNoExtraApp: String get() = map["onboardingCrossPlayNoExtraApp"] ?: "No extra app for players"
    val onboardingCrossPlayNoExtraAppBody: String get() = map["onboardingCrossPlayNoExtraAppBody"] ?: "Share your server address and players can connect from their own edition right away."
    val onboardingCrossPlayExperimental: String get() = map["onboardingCrossPlayExperimental"] ?: "Experimental Feature - Play at Your Own Discretion\n\nCross-play is still in active development. Bugs and stability issues may occur as this feature is not yet officially supported. Use at your own risk."
    val onboardingRegionTitle: String get() = map["onboardingRegionTitle"] ?: "Choose your relay region"
    val onboardingRegionSubtitle: String get() = map["onboardingRegionSubtitle"] ?: "Pick the relay server closest to your players. You can change this later anytime in the app."
    val onboardingRegionFinding: String get() = map["onboardingRegionFinding"] ?: "Finding best server..."
    val onboardingRegionRecommended: String get() = map["onboardingRegionRecommended"] ?: "Recommended: %s. You can still change it below."
    val onboardingPermissionsComplete: String get() = map["onboardingPermissionsComplete"] ?: "Permission complete"
    val onboardingPermissionsRequired: String get() = map["onboardingPermissionsRequired"] ?: "Required before continuing"
    val onboardingPermissionsTitle: String get() = map["onboardingPermissionsTitle"] ?: "Allow notifications"
    val onboardingPermissionsSubtitle: String get() = map["onboardingPermissionsSubtitle"] ?: "This is used for server status, player count, and important background updates while your server is running."
    val onboardingPermissionsCardTitle: String get() = map["onboardingPermissionsCardTitle"] ?: "Notifications"
    val onboardingPermissionsCardBody: String get() = map["onboardingPermissionsCardBody"] ?: "Shows server status and player count while the server is running."
    val onboardingPermissionsButtonEnabled: String get() = map["onboardingPermissionsButtonEnabled"] ?: "NOTIFICATIONS ENABLED"
    val onboardingPermissionsButtonAllow: String get() = map["onboardingPermissionsButtonAllow"] ?: "ALLOW NOTIFICATIONS"
    val onboardingPermissionsStatusSet: String get() = map["onboardingPermissionsStatusSet"] ?: "You\'re all set. Tap Next to keep going."
    val onboardingPermissionsStatusWarn: String get() = map["onboardingPermissionsStatusWarn"] ?: "Notification access is required on this step. Tap the button above, then allow it in Android."
    val onboardingPermissionsStatusTap: String get() = map["onboardingPermissionsStatusTap"] ?: "Tap the button above, then accept the Android permission prompt to unlock Next."
    val onboardingPermissionsError: String get() = map["onboardingPermissionsError"] ?: "Allow notification permission to continue."
    val onboardingGoogleTitle: String get() = map["onboardingGoogleTitle"] ?: "Optional Google sign-in"
    val onboardingGoogleSubtitle: String get() = map["onboardingGoogleSubtitle"] ?: "Sign in now to enable private Google Drive backups. You can skip this and finish setup first."
    val onboardingGoogleStatusTitle: String get() = map["onboardingGoogleStatusTitle"] ?: "Cloud Sync Status"
    val onboardingGoogleConnectedTitle: String get() = map["onboardingGoogleConnectedTitle"] ?: "Backup Account Connected"
    val onboardingGoogleStatusInactive: String get() = map["onboardingGoogleStatusInactive"] ?: "Inactive (Local Only)"
    val onboardingGoogleStatusActive: String get() = map["onboardingGoogleStatusActive"] ?: "Active & Secured"
    val onboardingGoogleStatusDesc: String get() = map["onboardingGoogleStatusDesc"] ?: "Backups are stored inside your private Google Drive app folder. PocketHost cannot see or access your other Drive files."
    val onboardingGoogleConnectedDesc: String get() = map["onboardingGoogleConnectedDesc"] ?: "Your server worlds, plugins, and settings will automatically backup to: %s"
    val onboardingGoogleSignInButton: String get() = map["onboardingGoogleSignInButton"] ?: "Sign in with Google"
    val onboardingGoogleSignedInButton: String get() = map["onboardingGoogleSignedInButton"] ?: "Signed in"
    val onboardingGoogleSkipNotice: String get() = map["onboardingGoogleSkipNotice"] ?: "You can press Next without signing in."
    val onboardingSetupTitle: String get() = map["onboardingSetupTitle"] ?: "Final setup"
    val onboardingSetupServerLabel: String get() = map["onboardingSetupServerLabel"] ?: "Server name (required)"
    val onboardingSetupWorldDescLabel: String get() = map["onboardingSetupWorldDescLabel"] ?: "World description (optional)"
    val onboardingSetupVersionPlaceholder: String get() = map["onboardingSetupVersionPlaceholder"] ?: "Select server type + version"
    val onboardingSetupCustomJar: String get() = map["onboardingSetupCustomJar"] ?: "%s (Custom JAR)"
    val onboardingSetupVersionLabel: String get() = map["onboardingSetupVersionLabel"] ?: "Game version (required)"
    val onboardingSetupVersionError: String get() = map["onboardingSetupVersionError"] ?: "Please select a game version"
    val onboardingSetupSeedLabel: String get() = map["onboardingSetupSeedLabel"] ?: "World seed (optional)"
    val onboardingSetupBackupNotice: String get() = map["onboardingSetupBackupNotice"] ?: "You can restore world backups later in Settings whenever you are ready."
    val onboardingSetupErrorServerName: String get() = map["onboardingSetupErrorServerName"] ?: "Server name is required."
    val onboardingSetupErrorVersion: String get() = map["onboardingSetupErrorVersion"] ?: "Game version is required."
    val onboardingButtonBack: String get() = map["onboardingButtonBack"] ?: "Back"
    val onboardingButtonSkip: String get() = map["onboardingButtonSkip"] ?: "Skip"
    val onboardingButtonFinish: String get() = map["onboardingButtonFinish"] ?: "Finish setup"
    val onboardingButtonGetStarted: String get() = map["onboardingButtonGetStarted"] ?: "Get started"
    val onboardingButtonNext: String get() = map["onboardingButtonNext"] ?: "Next"
    val onboardingScrollDown: String get() = map["onboardingScrollDown"] ?: "Scroll down"
}



fun appStringsFor(context: Context, lang: String): AppStrings {
    val targetLang = if (lang == "system" || lang.isEmpty()) {
        java.util.Locale.getDefault().language
    } else {
        lang
    }
    if (targetLang == "en" || targetLang.startsWith("en_") || targetLang.startsWith("en-")) {
        return AppStrings()
    }
    return try {
        val assetPath = "locales/$targetLang.json"
        val jsonStr = context.assets.open(assetPath).bufferedReader().use { it.readText() }
        val type = object : com.google.gson.reflect.TypeToken<Map<String, String>>() {}.type
        val map: Map<String, String> = Gson().fromJson(jsonStr, type) ?: emptyMap()
        AppStrings(map)
    } catch (e: Exception) {
        if (targetLang.contains("-") || targetLang.contains("_")) {
            val base = targetLang.split('-', '_')[0]
            if (base != "en") {
                try {
                    val assetPath = "locales/$base.json"
                    val jsonStr = context.assets.open(assetPath).bufferedReader().use { it.readText() }
                    val type = object : com.google.gson.reflect.TypeToken<Map<String, String>>() {}.type
                    val map: Map<String, String> = Gson().fromJson(jsonStr, type) ?: emptyMap()
                    return AppStrings(map)
                } catch (e2: Exception) {
                    // fall through
                }
            }
        }
        AppStrings()
    }
}

val LocalAppStrings = compositionLocalOf { AppStrings() }
