package com.pocketcraft.server.util

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    // Nav tabs
    val tabHome: String = "Home",
    val tabPlayers: String = "Players",
    val tabStorage: String = "Storage",
    val tabMods: String = "Mods",
    val tabSettings: String = "Settings",
    // Server controls
    val startServer: String = "START SERVER",
    val stopServer: String = "STOP",
    val restartServer: String = "RESTART",
    val starting: String = "STARTING...",
    val stopping: String = "STOPPING...",
    val restarting: String = "RESTARTING...",
    val offline: String = "OFFLINE",
    val online: String = "ONLINE",
    // Server card
    val yourServer: String = "YOUR SERVER",
    val hostedOn: String = "Hosted on PocketCraft",
    val tapToSwap: String = "One tap to swap your world or edit details",
    val stopToSwitch: String = "Stop the server to switch worlds",
    val tapToChangeVersion: String = "Tap to change version",
    val upgrade: String = "UPGRADE",
    // RAM
    val ramAllocation: String = "RAM Allocation",
    val ramLow: String = "Low",
    val ramManual: String = "Manual",
    val ramFull: String = "Full",
    val ramHighPerf: String = "High-performance preset — may cause overheating",
    val ramLowPerf: String = "Low-performance preset — saves battery",
    val ramManualHint: String = "Set a custom RAM allocation",
    // Console
    val console: String = "CONSOLE",
    val clearLog: String = "Clear",
    val sendCommand: String = "Send command",
    // Players
    val players: String = "Players",
    val tabOnline: String = "Online",
    val tabAllPlayers: String = "All Players",
    val tabWhitelist: String = "Whitelist",
    val tabOps: String = "Ops",
    val tabBanned: String = "Banned",
    val kick: String = "Kick",
    val ban: String = "Ban",
    val makeOp: String = "Make OP",
    val removeOp: String = "Remove OP",
    val unban: String = "Unban",
    val addPlayer: String = "Add Player",
    // Storage
    val worlds: String = "Worlds",
    val files: String = "Files",
    val share: String = "Share",
    val delete: String = "Delete",
    val view: String = "View",
    val close: String = "Close",
    val folder: String = "Folder",
    val uploading: String = "Uploading...",
    val chooseAction: String = "Choose an action",
    val unableToOpen: String = "Unable to open file.",
    // Settings sections
    val settingsServer: String = "Server",
    val settingsApp: String = "App",
    val settingsAbout: String = "About",
    val performance: String = "PERFORMANCE & OPTIMIZATION",
    val worldSettings: String = "WORLD SETTINGS",
    val networking: String = "NETWORKING",
    val appPreferences: String = "APP PREFERENCES",
    val sectionDeviceStorage: String = "DEVICE STORAGE",
    val sectionAbout: String = "ABOUT",
    // Settings labels
    val viewDistance: String = "View Distance",
    val viewDistanceDesc: String = "How far chunks are loaded",
    val viewDistanceHint: String = "Lower values recommended for low-end devices",
    val simulationDistance: String = "Simulation Distance",
    val simulationDistanceDesc: String = "Tick distance for mobs/crops",
    val maxPowerMode: String = "Max Power Mode",
    val maxPowerModeDesc: String = "Uses full RAM and max render distance. May cause overheating.",
    val mobSpawning: String = "Mob Spawning Optimization",
    val mobSpawningDesc: String = "Reduces entity count for better performance",
    val mobSpawningStandard: String = "Standard (Vanilla)",
    val difficulty: String = "Difficulty",
    val gamemode: String = "Gamemode",
    val whitelist: String = "Whitelist",
    val maxPlayers: String = "Max Players",
    val broadcastConsole: String = "Broadcast Console To Ops",
    val onlineMode: String = "Online Mode",
    val autoRestart: String = "Auto Restart",
    val autoRestartDesc: String = "Restart server automatically on crash",
    val forceExternalJvm: String = "Force External JVM",
    val forceExternalJvmDesc: String = "Use an external JVM instead of the bundled one",
    val configEditor: String = "Advanced Config Editor",
    val configEditorDesc: String = "Edit server.properties directly",
    val openFolder: String = "Open Server Folder",
    val openFolderDesc: String = "Browse server files in your file manager",
    val legalCenter: String = "Legal Center",
    val legalCenterDesc: String = "Privacy Policy & Licenses",
    val unsavedChanges: String = "Unsaved Changes",
    val failedToSave: String = "Failed to Save",
    val retry: String = "Retry",
    val save: String = "Save",
    val saving: String = "Saving...",
    val saved: String = "Saved",
    // Language
    val appLanguage: String = "App Language",
    val chooseLanguage: String = "Choose your preferred language",
    // Seed dialog
    val setWorldSeed: String = "Set World Seed",
    val worldSeedLabel: String = "World Seed (optional)",
    // Mods / Plugins screen
    val downloaded: String = "Downloaded",
    val managePluginsDesc: String = "Manage installed plugins and resource packs",
    val add: String = "Add",
    val mods: String = "Mods",
    val resourcePacks: String = "Resource Packs",
    val noModsInstalled: String = "No mods installed yet",
    val noResourcePacksInstalled: String = "No resource packs installed yet",
    val useAddButton: String = "Use the Add button to import a file, or install one from the discover screen.",
    val uploadFromDevice: String = "Upload from device",
    val pasteUrl: String = "Paste direct download URL",
    val download: String = "Download",
    val deleteConfirmDesc: String = "This removes the file from the current server version.",
    val enabled: String = "Enabled",
    val disabled: String = "Disabled",
    // PluginsSection component
    val addPlugin: String = "Add Plugin",
    val pluginsTip: String = "Upload Bukkit/Spigot/Paper compatible .jar plugins. Find plugins at spigotmc.org or hangar.papermc.io",
    val noPluginsInstalled: String = "No plugins installed",
    val tapToAddPlugin: String = "Tap 'Add Plugin' to upload a .jar file",
    // Common
    val cancel: String = "Cancel",
    val accept: String = "ACCEPT",
    val enable: String = "Enable",
    val disable: String = "Disable",
    val noInternetConnection: String = "No internet connection. Please check your network.",
    // PluginsHubScreen
    val hubTabPlugins: String = "Plugins",
    val hubTabMods: String = "Mods",
    val hubTabResourcePacks: String = "Resource Packs",
    val hubSearchPlaceholder: String = "Search online %s...",
    val hubModLoaderRequired: String = "Mod loader required for mods",
    val hubModLoaderDesc: String = "This server version is not using a supported mod loader. Switch this server to Fabric or Quilt to install mods.",
    val hubAddingFile: String = "Adding file: %d%%",
    val hubDownloading: String = "Downloading: %d%%",
    val hubSectionDownloaded: String = "Downloaded",
    val hubSectionDownloadedDesc: String = "Manage what is already stored for this server version.",
    val hubSectionDiscover: String = "Discover Online",
    val hubSectionDiscoverDesc: String = "Only online results are shown here. Installed matches are marked for you.",
    val hubTapToExpand: String = "Tap arrow to expand",
    val hubNoDownloaded: String = "No downloaded %s yet for this version.",
    val hubNoOnlineResults: String = "No online %s matched this search.",
    val hubLoadingOnline: String = "Loading online results...",
    val hubRetry: String = "Retry",
    val hubAdd: String = "Add",
    val hubInstall: String = "Install",
    val hubInstalling: String = "Installing...",
    val hubInstalled: String = "Installed",
    val hubSupportedMod: String = "Supported Mod",
    val hubUnsupported: String = "Unsupported",
    val hubUploadFromDevice: String = "Upload from device",
    val hubPasteUrl: String = "Paste direct download URL",
    val hubDownloadAction: String = "Download",
    val hubDeleteTitle: String = "Delete %s?",
    val hubDeleteDesc: String = "This will permanently remove the file from this server version.",
    val hubDeleteAction: String = "Delete",
    val hubSearchRetry: String = "Searches are cached and rate-limited, so retrying in a moment usually works.",
    val hubDetailFile: String = "File",
    val hubDetailVersion: String = "Version",
    val hubDetailSize: String = "Size",
    val hubDetailApply: String = "Apply",
    val hubDetailApplyDesc: String = "Restart the server after changing plugins or packs.",
    val hubDetailVersionNotProvided: String = "Not provided",
    val hubDetailDownloads: String = "Downloads",
    val hubDetailSource: String = "Source",
    val hubDetailSlug: String = "Slug",
    val hubDetailDescription: String = "Description",
    val hubDetailSupport: String = "Support",
    val hubCommunityListing: String = "Community listing",
    val hubEnabledStatus: String = "Enabled",
    val hubDisabledStatus: String = "Disabled",
    // WorldsScreen
    val worldsSectionCurrentWorld: String = "CURRENT WORLD",
    val worldsMbOnDisk: String = "%s MB on disk",
    val worldsBackingUp: String = "BACKING UP...",
    val worldsBackup: String = "BACKUP",
    val worldsReset: String = "RESET",
    val worldsStopBeforeReset: String = "Stop the server before resetting the world.",
    val worldsSectionSlots: String = "WORLD SLOTS",
    val worldsAdd: String = "ADD",
    val worldsSlotHint: String = "Slide left to delete. Active worlds can only be deleted when the server is stopped.",
    val worldsSectionImport: String = "IMPORT DIMENSIONS",
    val worldsImportGuideTitle: String = "Import guide",
    val worldsImportGuideDesc: String = "Tap to see how world and dimension imports work.",
    val worldsUploadOverworld: String = "Upload Overworld",
    val worldsUploadNether: String = "Upload Nether",
    val worldsUploadEnd: String = "Upload The End",
    val worldsOverworldSub: String = "Main world (%s)",
    val worldsNetherSub: String = "Nether dimension (%s_nether)",
    val worldsEndSub: String = "End dimension (%s_the_end)",
    val worldsSectionBackupHistory: String = "BACKUP HISTORY",
    val worldsFiles: String = "%d files",
    val worldsNoBackups: String = "No backups found",
    val worldsStopToSwitch: String = "Stop server to switch worlds",
    val worldsStopToUpload: String = "Stop server to upload",
    val worldsExtracted: String = "%d%% extracted",
    val worldsUpload: String = "UPLOAD",
    val worldsActive: String = "ACTIVE",
    val worldsDelete: String = "Delete",
    // Reset dialog
    val worldsResetTitle: String = "⚠️ Reset World",
    val worldsResetDesc: String = "Choose what to delete. Plugins, mods, config files, and server.properties will be preserved.",
    val worldsResetRowWorld: String = "World folders (world, world_nether, world_the_end)",
    val worldsResetRowPlayers: String = "Player data (playerdata, stats, advancements)",
    val worldsResetRowDatapacks: String = "Datapacks",
    val worldsResetRowLogs: String = "Logs",
    val worldsResetPreserved: String = "Always preserved: plugins/, mods/, config/, server.properties, and config files.",
    val worldsResetDeleteSelected: String = "DELETE SELECTED",
    val worldsCancel: String = "CANCEL",
    // Restore dialog
    val worldsRestoreTitle: String = "Restore Backup?",
    val worldsRestoreDesc: String = "This will restore:\n- Worlds and dimension data\n- Plugins, mods, and resource packs\n- Server configs and settings\n\nYour current server files will be overwritten.\nMake sure the server is stopped before restoring.",
    val worldsRestoreAction: String = "RESTORE",
    // Delete backup dialog
    val worldsDeleteBackupTitle: String = "Delete Backup?",
    val worldsDeleteBackupDesc: String = "Are you sure you want to delete %s?",
    val worldsDeleteAction: String = "DELETE",
    // Delete world dialog
    val worldsDeleteWorldTitle: String = "Delete World?",
    val worldsDeleteWorldActive: String = "Delete %s? PocketCraft will switch to another saved world first.",
    val worldsDeleteWorldInactive: String = "Delete %s? This removes the world from storage.",
    // Import guide dialog
    val worldsImportGuideSheetTitle: String = "Import Guide",
    val worldsImportGuideText1: String = "Aternos exports can be uploaded as 3 separate ZIPs: Overworld, Nether, and The End.",
    val worldsImportGuideText2: String = "Most other world backups already include all dimensions in one archive, so a single world backup import is enough.",
    val worldsImportGuideClose: String = "CLOSE",
    // FilesScreen
    val filesSectionCurrentWorld: String = "CURRENT WORLD",
    val filesActiveFolder: String = "Active folder • %sMB",
    val filesDeleteActiveWorld: String = "DELETE ACTIVE WORLD",
    val filesAddAnotherWorld: String = "Add another world before deleting this one.",
    val filesSectionSeed: String = "WORLD SEED",
    val filesSeedRandom: String = "Random",
    val filesSeedUsedFor: String = "Seed used for generation",
    val filesSeedCopied: String = "Seed copied to clipboard.",
    val filesSeedEdit: String = "EDIT",
    val filesSectionCore: String = "SERVER CORE",
    val filesMinecraftJava: String = "Minecraft Java %s",
    val filesSwitchOrUpgrade: String = "Switch or upgrade",
    val filesChange: String = "CHANGE",
    val filesSectionBackup: String = "BACKUP & MAINTENANCE",
    val filesQuickBackup: String = "Quick Backup",
    val filesAdvanced: String = "Advanced...",
    val filesSeedDialogTitle: String = "Set World Seed",
    val filesSeedDialogDesc: String = "Enter a seed for your world. Leave it empty for a random world.",
    val filesSeedDialogLabel: String = "World Seed (optional)",
    val filesSeedDialogConfirm: String = "CONFIRM",
    val filesSeedDialogCancel: String = "CANCEL",
    val filesDeleteWorldTitle: String = "Delete Active World?",
    val filesDeleteWorldDesc: String = "This will permanently delete %s and switch to another saved world if one exists.",
    val filesDeleteAction: String = "DELETE",
    val filesDeleteCancel: String = "CANCEL"
)

val German = AppStrings(
    tabHome = "Start", tabPlayers = "Spieler", tabStorage = "Speicher", tabMods = "Mods", tabSettings = "Einstellungen",
    startServer = "SERVER STARTEN", stopServer = "STOP", restartServer = "NEUSTART",
    starting = "WIRD GESTARTET...", stopping = "WIRD GESTOPPT...", restarting = "NEUSTART...",
    offline = "OFFLINE", online = "ONLINE",
    yourServer = "IHR SERVER", hostedOn = "Gehostet auf PocketCraft",
    tapToSwap = "Tippen um Welt zu wechseln oder Details zu bearbeiten",
    stopToSwitch = "Server stoppen um Welten zu wechseln",
    tapToChangeVersion = "Tippen um Version zu ändern", upgrade = "UPGRADE",
    ramAllocation = "RAM-Zuweisung", ramLow = "Niedrig", ramManual = "Manuell", ramFull = "Voll",
    ramHighPerf = "Hochleistungs-Preset — kann Überhitzung verursachen",
    ramLowPerf = "Niedriges Preset — spart Akku", ramManualHint = "Manuelle RAM-Zuweisung",
    console = "KONSOLE", clearLog = "Löschen", sendCommand = "Befehl senden",
    players = "Spieler", tabOnline = "Online", tabAllPlayers = "Alle Spieler",
    tabWhitelist = "Whitelist", tabOps = "Ops", tabBanned = "Gebannt",
    kick = "Kicken", ban = "Bannen", makeOp = "OP ernennen", removeOp = "OP entfernen",
    unban = "Entbannen", addPlayer = "Spieler hinzufügen",
    worlds = "Welten", files = "Dateien", share = "Teilen", delete = "Löschen",
    view = "Ansehen", close = "Schließen", folder = "Ordner",
    uploading = "Hochladen...", chooseAction = "Aktion wählen", unableToOpen = "Datei kann nicht geöffnet werden.",
    settingsServer = "Server", settingsApp = "App", settingsAbout = "Info",
    performance = "LEISTUNG & OPTIMIERUNG", worldSettings = "WELTEINSTELLUNGEN",
    networking = "NETZWERK", appPreferences = "APP-EINSTELLUNGEN",
    sectionDeviceStorage = "GERÄTESPEICHER", sectionAbout = "ÜBER",
    viewDistance = "Sichtweite", viewDistanceDesc = "Wie weit Chunks geladen werden",
    viewDistanceHint = "Niedrige Werte für schwache Geräte empfohlen",
    simulationDistance = "Simulationsdistanz", simulationDistanceDesc = "Tick-Distanz für Mobs/Pflanzen",
    maxPowerMode = "Max-Power-Modus", maxPowerModeDesc = "Verwendet vollen RAM und maximale Sichtweite. Kann Überhitzung verursachen.",
    mobSpawning = "Mob-Spawn-Optimierung", mobSpawningDesc = "Reduziert Entitätsanzahl für bessere Performance",
    mobSpawningStandard = "Standard (Vanilla)",
    difficulty = "Schwierigkeit", gamemode = "Spielmodus", whitelist = "Whitelist",
    maxPlayers = "Max. Spieler", broadcastConsole = "Konsole an Ops senden",
    onlineMode = "Online-Modus", autoRestart = "Auto-Neustart",
    autoRestartDesc = "Server bei Absturz automatisch neu starten",
    forceExternalJvm = "Externe JVM erzwingen", forceExternalJvmDesc = "Externe JVM statt der integrierten verwenden",
    configEditor = "Erweiterter Konfig-Editor", configEditorDesc = "server.properties direkt bearbeiten",
    openFolder = "Serverordner öffnen", openFolderDesc = "Serverdateien im Dateimanager durchsuchen",
    legalCenter = "Rechtszentrum", legalCenterDesc = "Datenschutzrichtlinie & Lizenzen",
    unsavedChanges = "Ungespeicherte Änderungen", failedToSave = "Speichern fehlgeschlagen",
    retry = "Wiederholen", save = "Speichern", saving = "Wird gespeichert...", saved = "Gespeichert",
    appLanguage = "App-Sprache", chooseLanguage = "Bevorzugte Sprache wählen",
    setWorldSeed = "Welt-Seed festlegen", worldSeedLabel = "Welt-Seed (optional)",
    downloaded = "Heruntergeladen", managePluginsDesc = "Installierte Plugins und Ressourcenpakete verwalten",
    add = "Hinzufügen", mods = "Mods", resourcePacks = "Ressourcenpakete",
    noModsInstalled = "Noch keine Mods installiert", noResourcePacksInstalled = "Noch keine Ressourcenpakete installiert",
    useAddButton = "Nutze die Hinzufügen-Schaltfläche, um eine Datei zu importieren.",
    uploadFromDevice = "Vom Gerät hochladen", pasteUrl = "Direkte Download-URL einfügen",
    download = "Herunterladen", deleteConfirmDesc = "Dies entfernt die Datei von der aktuellen Serverversion.",
    enabled = "Aktiviert", disabled = "Deaktiviert",
    addPlugin = "Plugin hinzufügen",
    pluginsTip = "Bukkit/Spigot/Paper .jar-Plugins hochladen. Plugins auf spigotmc.org finden.",
    noPluginsInstalled = "Keine Plugins installiert", tapToAddPlugin = "Tippe 'Plugin hinzufügen' um eine .jar-Datei hochzuladen",
    cancel = "Abbrechen", accept = "AKZEPTIEREN", enable = "Aktivieren", disable = "Deaktivieren",
    noInternetConnection = "Keine Internetverbindung. Bitte Netzwerk prüfen.",
    hubTabPlugins = "Plugins", hubTabMods = "Mods", hubTabResourcePacks = "Ressourcenpakete",
    hubSearchPlaceholder = "Online %s suchen...",
    hubModLoaderRequired = "Mod-Loader für Mods erforderlich",
    hubModLoaderDesc = "Diese Serverversion verwendet keinen unterstützten Mod-Loader. Wechsle zu Fabric oder Quilt.",
    hubAddingFile = "Datei hinzufügen: %d%%", hubDownloading = "Herunterladen: %d%%",
    hubSectionDownloaded = "Heruntergeladen", hubSectionDownloadedDesc = "Verwalte, was für diese Serverversion gespeichert ist.",
    hubSectionDiscover = "Online entdecken", hubSectionDiscoverDesc = "Hier werden nur Online-Ergebnisse angezeigt. Installierte Treffer sind markiert.",
    hubTapToExpand = "Pfeil zum Aufklappen tippen",
    hubNoDownloaded = "Noch keine %s für diese Version heruntergeladen.",
    hubNoOnlineResults = "Keine Online-%s für diese Suche gefunden.",
    hubLoadingOnline = "Online-Ergebnisse laden...",
    hubRetry = "Wiederholen", hubAdd = "Hinzufügen", hubInstall = "Installieren",
    hubInstalling = "Installieren...", hubInstalled = "Installiert",
    hubSupportedMod = "Unterstützter Mod", hubUnsupported = "Nicht unterstützt",
    hubUploadFromDevice = "Vom Gerät hochladen", hubPasteUrl = "Direkte Download-URL einfügen",
    hubDownloadAction = "Herunterladen",
    hubDeleteTitle = "%s löschen?", hubDeleteDesc = "Dies entfernt die Datei dauerhaft aus dieser Serverversion.",
    hubDeleteAction = "Löschen",
    hubSearchRetry = "Suchanfragen sind gecacht und gedrosselt. Kurz warten und erneut versuchen.",
    hubDetailFile = "Datei", hubDetailVersion = "Version", hubDetailSize = "Größe",
    hubDetailApply = "Anwenden", hubDetailApplyDesc = "Server nach Änderungen neu starten.",
    hubDetailVersionNotProvided = "Nicht angegeben",
    hubDetailDownloads = "Downloads", hubDetailSource = "Quelle", hubDetailSlug = "Slug",
    hubDetailDescription = "Beschreibung", hubDetailSupport = "Support",
    hubCommunityListing = "Community-Eintrag",
    hubEnabledStatus = "Aktiviert", hubDisabledStatus = "Deaktiviert",
    worldsSectionCurrentWorld = "AKTUELLE WELT", worldsMbOnDisk = "%s MB auf dem Gerät",
    worldsBackingUp = "WIRD GESICHERT...", worldsBackup = "SICHERN", worldsReset = "ZURÜCKSETZEN",
    worldsStopBeforeReset = "Server stoppen, bevor die Welt zurückgesetzt wird.",
    worldsSectionSlots = "WELTPLÄTZE", worldsAdd = "HINZUFÜGEN",
    worldsSlotHint = "Links wischen zum Löschen. Aktive Welten können nur gestoppt gelöscht werden.",
    worldsSectionImport = "DIMENSIONEN IMPORTIEREN",
    worldsImportGuideTitle = "Import-Anleitung", worldsImportGuideDesc = "Tippen für Infos zum Import.",
    worldsUploadOverworld = "Oberwelt hochladen", worldsUploadNether = "Nether hochladen", worldsUploadEnd = "End hochladen",
    worldsOverworldSub = "Hauptwelt (%s)", worldsNetherSub = "Nether-Dimension (%s_nether)", worldsEndSub = "End-Dimension (%s_the_end)",
    worldsSectionBackupHistory = "SICHERUNGSVERLAUF", worldsFiles = "%d Dateien",
    worldsNoBackups = "Keine Sicherungen gefunden", worldsStopToSwitch = "Server stoppen um Welten zu wechseln",
    worldsStopToUpload = "Server stoppen zum Hochladen", worldsExtracted = "%d%% extrahiert",
    worldsUpload = "HOCHLADEN", worldsActive = "AKTIV", worldsDelete = "Löschen",
    worldsResetTitle = "⚠️ Welt zurücksetzen",
    worldsResetDesc = "Wähle was gelöscht werden soll. Plugins, Mods, Configs und server.properties bleiben erhalten.",
    worldsResetRowWorld = "Weltordner (world, world_nether, world_the_end)",
    worldsResetRowPlayers = "Spielerdaten (playerdata, stats, advancements)",
    worldsResetRowDatapacks = "Datenpakete", worldsResetRowLogs = "Logs",
    worldsResetPreserved = "Immer erhalten: plugins/, mods/, config/, server.properties.",
    worldsResetDeleteSelected = "AUSGEWÄHLTE LÖSCHEN", worldsCancel = "ABBRECHEN",
    worldsRestoreTitle = "Sicherung wiederherstellen?",
    worldsRestoreDesc = "Wiederhergestellt werden:\n- Welten und Dimensionen\n- Plugins, Mods, Ressourcenpakete\n- Serverkonfigurationen\n\nAktuelle Dateien werden überschrieben.\nServer muss gestoppt sein.",
    worldsRestoreAction = "WIEDERHERSTELLEN",
    worldsDeleteBackupTitle = "Sicherung löschen?", worldsDeleteBackupDesc = "Sicherung '%s' wirklich löschen?",
    worldsDeleteAction = "LÖSCHEN",
    worldsDeleteWorldTitle = "Welt löschen?",
    worldsDeleteWorldActive = "%s löschen? PocketCraft wechselt zur nächsten Welt.",
    worldsDeleteWorldInactive = "%s löschen? Die Welt wird vom Speicher entfernt.",
    worldsImportGuideSheetTitle = "Import-Anleitung",
    worldsImportGuideText1 = "Aternos-Exporte können als 3 separate ZIPs hochgeladen werden: Oberwelt, Nether und End.",
    worldsImportGuideText2 = "Die meisten Sicherungen enthalten alle Dimensionen in einem Archiv.",
    worldsImportGuideClose = "SCHLIEẞEN",
    filesSectionCurrentWorld = "AKTUELLE WELT", filesActiveFolder = "Aktiver Ordner • %s MB",
    filesDeleteActiveWorld = "AKTIVE WELT LÖSCHEN",
    filesAddAnotherWorld = "Füge eine weitere Welt hinzu, bevor du diese löschst.",
    filesSectionSeed = "WELT-SEED", filesSeedRandom = "Zufällig",
    filesSeedUsedFor = "Seed für die Weltgenerierung", filesSeedCopied = "Seed in Zwischenablage kopiert.",
    filesSeedEdit = "BEARBEITEN", filesSectionCore = "SERVER-KERN",
    filesMinecraftJava = "Minecraft Java %s", filesSwitchOrUpgrade = "Wechseln oder aktualisieren",
    filesChange = "ÄNDERN", filesSectionBackup = "SICHERUNG & WARTUNG",
    filesQuickBackup = "Schnellsicherung", filesAdvanced = "Erweitert...",
    filesSeedDialogTitle = "Welt-Seed festlegen",
    filesSeedDialogDesc = "Gib einen Seed ein oder leer lassen für zufällig.",
    filesSeedDialogLabel = "Welt-Seed (optional)", filesSeedDialogConfirm = "BESTÄTIGEN", filesSeedDialogCancel = "ABBRECHEN",
    filesDeleteWorldTitle = "Aktive Welt löschen?",
    filesDeleteWorldDesc = "%s wird dauerhaft gelöscht und zu einer anderen Welt gewechselt.",
    filesDeleteAction = "LÖSCHEN", filesDeleteCancel = "ABBRECHEN"
)

val Spanish = AppStrings(
    tabHome = "Inicio", tabPlayers = "Jugadores", tabStorage = "Almacenamiento", tabMods = "Mods", tabSettings = "Ajustes",
    startServer = "INICIAR SERVIDOR", stopServer = "DETENER", restartServer = "REINICIAR",
    starting = "INICIANDO...", stopping = "DETENIENDO...", restarting = "REINICIANDO...",
    offline = "DESCONECTADO", online = "EN LÍNEA",
    yourServer = "TU SERVIDOR", hostedOn = "Alojado en PocketCraft",
    tapToSwap = "Un toque para cambiar mundo o editar detalles",
    stopToSwitch = "Detén el servidor para cambiar mundos",
    tapToChangeVersion = "Toca para cambiar versión", upgrade = "ACTUALIZAR",
    ramAllocation = "Asignación de RAM", ramLow = "Baja", ramManual = "Manual", ramFull = "Completa",
    ramHighPerf = "Preset de alto rendimiento — puede causar sobrecalentamiento",
    ramLowPerf = "Preset de bajo rendimiento — ahorra batería", ramManualHint = "Establecer RAM personalizada",
    console = "CONSOLA", clearLog = "Limpiar", sendCommand = "Enviar comando",
    players = "Jugadores", tabOnline = "En línea", tabAllPlayers = "Todos",
    tabWhitelist = "Lista blanca", tabOps = "Ops", tabBanned = "Baneados",
    kick = "Expulsar", ban = "Banear", makeOp = "Hacer OP", removeOp = "Quitar OP",
    unban = "Desbanear", addPlayer = "Añadir jugador",
    worlds = "Mundos", files = "Archivos", share = "Compartir", delete = "Eliminar",
    view = "Ver", close = "Cerrar", folder = "Carpeta",
    uploading = "Subiendo...", chooseAction = "Elige una acción", unableToOpen = "No se puede abrir el archivo.",
    settingsServer = "Servidor", settingsApp = "App", settingsAbout = "Acerca de",
    performance = "RENDIMIENTO Y OPTIMIZACIÓN", worldSettings = "CONFIGURACIÓN DEL MUNDO",
    networking = "RED", appPreferences = "PREFERENCIAS",
    sectionDeviceStorage = "ALMACENAMIENTO", sectionAbout = "ACERCA DE",
    viewDistance = "Distancia de visión", viewDistanceDesc = "Qué tan lejos se cargan los chunks",
    viewDistanceHint = "Valores bajos recomendados para dispositivos débiles",
    simulationDistance = "Distancia de simulación", simulationDistanceDesc = "Distancia de tick para mobs/cultivos",
    maxPowerMode = "Modo Max Potencia", maxPowerModeDesc = "Usa toda la RAM y máxima distancia. Puede sobrecalentar.",
    mobSpawning = "Optimización de Mobs", mobSpawningDesc = "Reduce entidades para mejor rendimiento",
    mobSpawningStandard = "Estándar (Vanilla)",
    difficulty = "Dificultad", gamemode = "Modo de juego", whitelist = "Lista blanca",
    maxPlayers = "Máx. jugadores", broadcastConsole = "Enviar consola a Ops",
    onlineMode = "Modo online", autoRestart = "Reinicio automático",
    autoRestartDesc = "Reiniciar servidor automáticamente al fallar",
    forceExternalJvm = "Forzar JVM externo", forceExternalJvmDesc = "Usar JVM externo en lugar del integrado",
    configEditor = "Editor de configuración", configEditorDesc = "Editar server.properties directamente",
    openFolder = "Abrir carpeta del servidor", openFolderDesc = "Explorar archivos en el gestor",
    legalCenter = "Centro legal", legalCenterDesc = "Política de privacidad y licencias",
    unsavedChanges = "Cambios sin guardar", failedToSave = "Error al guardar",
    retry = "Reintentar", save = "Guardar", saving = "Guardando...", saved = "Guardado",
    appLanguage = "Idioma de la app", chooseLanguage = "Elige tu idioma preferido",
    setWorldSeed = "Establecer semilla", worldSeedLabel = "Semilla del mundo (opcional)",
    downloaded = "Descargado", managePluginsDesc = "Gestiona plugins y paquetes de recursos instalados",
    add = "Añadir", mods = "Mods", resourcePacks = "Paquetes de recursos",
    noModsInstalled = "Aún no hay mods instalados", noResourcePacksInstalled = "Aún no hay paquetes de recursos instalados",
    useAddButton = "Usa el botón Añadir para importar un archivo o instala uno desde la pantalla de descubrimiento.",
    uploadFromDevice = "Subir desde dispositivo", pasteUrl = "Pega URL de descarga directa",
    download = "Descargar", deleteConfirmDesc = "Esto elimina el archivo de la versión actual del servidor.",
    enabled = "Activado", disabled = "Desactivado",
    addPlugin = "Añadir plugin",
    pluginsTip = "Sube plugins .jar compatibles con Bukkit/Spigot/Paper. Encuéntralos en spigotmc.org.",
    noPluginsInstalled = "No hay plugins instalados", tapToAddPlugin = "Toca 'Añadir plugin' para subir un .jar",
    cancel = "Cancelar", accept = "ACEPTAR", enable = "Activar", disable = "Desactivar",
    noInternetConnection = "Sin conexión a internet. Verifica tu red.",
    hubTabPlugins = "Plugins", hubTabMods = "Mods", hubTabResourcePacks = "Paquetes de recursos",
    hubSearchPlaceholder = "Buscar %s en línea...",
    hubModLoaderRequired = "Se requiere cargador de mods",
    hubModLoaderDesc = "Esta versión del servidor no usa un cargador de mods compatible. Cambia a Fabric o Quilt.",
    hubAddingFile = "Añadiendo archivo: %d%%", hubDownloading = "Descargando: %d%%",
    hubSectionDownloaded = "Descargado", hubSectionDownloadedDesc = "Gestiona lo que ya está almacenado para esta versión del servidor.",
    hubSectionDiscover = "Descubrir en línea", hubSectionDiscoverDesc = "Aquí solo se muestran resultados en línea. Los coincidentes instalados están marcados.",
    hubTapToExpand = "Toca la flecha para expandir",
    hubNoDownloaded = "Aún no hay %s descargados para esta versión.",
    hubNoOnlineResults = "Ningún %s en línea coincidió con esta búsqueda.",
    hubLoadingOnline = "Cargando resultados en línea...",
    hubRetry = "Reintentar", hubAdd = "Añadir", hubInstall = "Instalar",
    hubInstalling = "Instalando...", hubInstalled = "Instalado",
    hubSupportedMod = "Mod compatible", hubUnsupported = "No compatible",
    hubUploadFromDevice = "Subir desde dispositivo", hubPasteUrl = "Pegar URL de descarga directa",
    hubDownloadAction = "Descargar",
    hubDeleteTitle = "¿Eliminar %s?", hubDeleteDesc = "Esto eliminará permanentemente el archivo de esta versión del servidor.",
    hubDeleteAction = "Eliminar",
    hubSearchRetry = "Las búsquedas están en caché y tienen límite. Reintenta en un momento.",
    hubDetailFile = "Archivo", hubDetailVersion = "Versión", hubDetailSize = "Tamaño",
    hubDetailApply = "Aplicar", hubDetailApplyDesc = "Reinicia el servidor tras cambiar plugins o paquetes.",
    hubDetailVersionNotProvided = "No proporcionada",
    hubDetailDownloads = "Descargas", hubDetailSource = "Fuente", hubDetailSlug = "Slug",
    hubDetailDescription = "Descripción", hubDetailSupport = "Soporte",
    hubCommunityListing = "Listado comunitario",
    hubEnabledStatus = "Activado", hubDisabledStatus = "Desactivado",
    worldsSectionCurrentWorld = "MUNDO ACTUAL", worldsMbOnDisk = "%s MB en disco",
    worldsBackingUp = "GUARDANDO...", worldsBackup = "GUARDAR", worldsReset = "RESTABLECER",
    worldsStopBeforeReset = "Detén el servidor antes de restablecer el mundo.",
    worldsSectionSlots = "RANURAS DE MUNDO", worldsAdd = "AÑADIR",
    worldsSlotHint = "Desliza a la izquierda para eliminar. Los mundos activos solo se pueden eliminar con el servidor detenido.",
    worldsSectionImport = "IMPORTAR DIMENSIONES",
    worldsImportGuideTitle = "Guía de importación", worldsImportGuideDesc = "Toca para ver cómo funcionan las importaciones.",
    worldsUploadOverworld = "Subir Mundo Superior", worldsUploadNether = "Subir Nether", worldsUploadEnd = "Subir The End",
    worldsOverworldSub = "Mundo principal (%s)", worldsNetherSub = "Dimensión Nether (%s_nether)", worldsEndSub = "Dimensión End (%s_the_end)",
    worldsSectionBackupHistory = "HISTORIAL DE COPIAS", worldsFiles = "%d archivos",
    worldsNoBackups = "No se encontraron copias", worldsStopToSwitch = "Detén el servidor para cambiar mundos",
    worldsStopToUpload = "Detén el servidor para subir", worldsExtracted = "%d%% extraído",
    worldsUpload = "SUBIR", worldsActive = "ACTIVO", worldsDelete = "Eliminar",
    worldsResetTitle = "⚠️ Restablecer mundo",
    worldsResetDesc = "Elige qué eliminar. Plugins, mods, configs y server.properties se conservarán.",
    worldsResetRowWorld = "Carpetas de mundo (world, world_nether, world_the_end)",
    worldsResetRowPlayers = "Datos de jugadores (playerdata, stats, advancements)",
    worldsResetRowDatapacks = "Datapacks", worldsResetRowLogs = "Logs",
    worldsResetPreserved = "Siempre conservado: plugins/, mods/, config/, server.properties.",
    worldsResetDeleteSelected = "ELIMINAR SELECCIONADO", worldsCancel = "CANCELAR",
    worldsRestoreTitle = "¿Restaurar copia?",
    worldsRestoreDesc = "Se restaurará:\n- Mundos y dimensiones\n- Plugins, mods y paquetes\n- Configuraciones del servidor\n\nLos archivos actuales serán sobreescritos.\nAsegúrate de detener el servidor.",
    worldsRestoreAction = "RESTAURAR",
    worldsDeleteBackupTitle = "¿Eliminar copia?", worldsDeleteBackupDesc = "¿Eliminar %s?",
    worldsDeleteAction = "ELIMINAR",
    worldsDeleteWorldTitle = "¿Eliminar mundo?",
    worldsDeleteWorldActive = "¿Eliminar %s? PocketCraft cambiará a otro mundo.",
    worldsDeleteWorldInactive = "¿Eliminar %s? El mundo se eliminará del almacenamiento.",
    worldsImportGuideSheetTitle = "Guía de importación",
    worldsImportGuideText1 = "Las exportaciones de Aternos pueden subirse como 3 ZIPs: Overworld, Nether y The End.",
    worldsImportGuideText2 = "La mayoría de copias ya incluyen todas las dimensiones en un solo archivo.",
    worldsImportGuideClose = "CERRAR",
    filesSectionCurrentWorld = "MUNDO ACTUAL", filesActiveFolder = "Carpeta activa • %s MB",
    filesDeleteActiveWorld = "ELIMINAR MUNDO ACTIVO",
    filesAddAnotherWorld = "Añade otro mundo antes de eliminar este.",
    filesSectionSeed = "SEMILLA DEL MUNDO", filesSeedRandom = "Aleatoria",
    filesSeedUsedFor = "Semilla para la generación", filesSeedCopied = "Semilla copiada al portapapeles.",
    filesSeedEdit = "EDITAR", filesSectionCore = "NÚCLEO DEL SERVIDOR",
    filesMinecraftJava = "Minecraft Java %s", filesSwitchOrUpgrade = "Cambiar o actualizar",
    filesChange = "CAMBIAR", filesSectionBackup = "COPIA & MANTENIMIENTO",
    filesQuickBackup = "Copia rápida", filesAdvanced = "Avanzado...",
    filesSeedDialogTitle = "Establecer semilla",
    filesSeedDialogDesc = "Introduce una semilla o déjala vacía para aleatoria.",
    filesSeedDialogLabel = "Semilla del mundo (opcional)", filesSeedDialogConfirm = "CONFIRMAR", filesSeedDialogCancel = "CANCELAR",
    filesDeleteWorldTitle = "¿Eliminar mundo activo?",
    filesDeleteWorldDesc = "%s se eliminará permanentemente y se cambiará a otro mundo.",
    filesDeleteAction = "ELIMINAR", filesDeleteCancel = "CANCELAR"
)

val Russian = AppStrings(
    tabHome = "Главная", tabPlayers = "Игроки", tabStorage = "Хранилище", tabMods = "Моды", tabSettings = "Настройки",
    startServer = "ЗАПУСТИТЬ СЕРВЕР", stopServer = "СТОП", restartServer = "ПЕРЕЗАПУСК",
    starting = "ЗАПУСК...", stopping = "ОСТАНОВКА...", restarting = "ПЕРЕЗАПУСК...",
    offline = "ОФЛАЙН", online = "ОНЛАЙН",
    yourServer = "ВАШ СЕРВЕР", hostedOn = "Хостинг на PocketCraft",
    tapToSwap = "Нажмите, чтобы сменить мир или изменить настройки",
    stopToSwitch = "Остановите сервер для смены мира",
    tapToChangeVersion = "Нажмите для смены версии", upgrade = "ОБНОВИТЬ",
    ramAllocation = "Выделение ОЗУ", ramLow = "Низкое", ramManual = "Ручное", ramFull = "Полное",
    ramHighPerf = "Высокопроизводительный пресет — может перегреться",
    ramLowPerf = "Низкопроизводительный пресет — экономит батарею", ramManualHint = "Ручное выделение ОЗУ",
    console = "КОНСОЛЬ", clearLog = "Очистить", sendCommand = "Отправить команду",
    players = "Игроки", tabOnline = "Онлайн", tabAllPlayers = "Все игроки",
    tabWhitelist = "Белый список", tabOps = "Операторы", tabBanned = "Заблокированные",
    kick = "Выгнать", ban = "Заблокировать", makeOp = "Назначить OP", removeOp = "Снять OP",
    unban = "Разблокировать", addPlayer = "Добавить игрока",
    worlds = "Миры", files = "Файлы", share = "Поделиться", delete = "Удалить",
    view = "Просмотр", close = "Закрыть", folder = "Папка",
    uploading = "Загрузка...", chooseAction = "Выберите действие", unableToOpen = "Невозможно открыть файл.",
    settingsServer = "Сервер", settingsApp = "Приложение", settingsAbout = "О программе",
    performance = "ПРОИЗВОДИТЕЛЬНОСТЬ", worldSettings = "НАСТРОЙКИ МИРА",
    networking = "СЕТЬ", appPreferences = "НАСТРОЙКИ ПРИЛОЖЕНИЯ",
    sectionDeviceStorage = "ХРАНИЛИЩЕ УСТРОЙСТВА", sectionAbout = "О ПРОГРАММЕ",
    viewDistance = "Дальность прорисовки", viewDistanceDesc = "Как далеко загружаются чанки",
    viewDistanceHint = "Низкие значения рекомендуются для слабых устройств",
    simulationDistance = "Дистанция симуляции", simulationDistanceDesc = "Дистанция тиков для мобов/посевов",
    maxPowerMode = "Режим максимальной мощности", maxPowerModeDesc = "Использует весь ОЗУ и максимальную дальность. Может перегреться.",
    mobSpawning = "Оптимизация мобов", mobSpawningDesc = "Уменьшает количество сущностей",
    mobSpawningStandard = "Стандарт (Vanilla)",
    difficulty = "Сложность", gamemode = "Режим игры", whitelist = "Белый список",
    maxPlayers = "Макс. игроков", broadcastConsole = "Трансляция консоли операторам",
    onlineMode = "Онлайн-режим", autoRestart = "Авто-перезапуск",
    autoRestartDesc = "Автоматически перезапускать сервер при сбое",
    forceExternalJvm = "Принудительный внешний JVM", forceExternalJvmDesc = "Использовать внешний JVM",
    configEditor = "Расширенный редактор", configEditorDesc = "Редактировать server.properties напрямую",
    openFolder = "Открыть папку сервера", openFolderDesc = "Обзор файлов в файловом менеджере",
    legalCenter = "Юридический центр", legalCenterDesc = "Политика конфиденциальности и лицензии",
    unsavedChanges = "Несохранённые изменения", failedToSave = "Не удалось сохранить",
    retry = "Повторить", save = "Сохранить", saving = "Сохранение...", saved = "Сохранено",
    appLanguage = "Язык приложения", chooseLanguage = "Выберите язык",
    setWorldSeed = "Установить сид мира", worldSeedLabel = "Сид мира (необязательно)",
    downloaded = "Загруженное", managePluginsDesc = "Управление установленными плагинами и ресурспаками",
    add = "Добавить", mods = "Моды", resourcePacks = "Ресурспаки",
    noModsInstalled = "Моды ещё не установлены", noResourcePacksInstalled = "Ресурспаки ещё не установлены",
    useAddButton = "Используйте кнопку 'Добавить', чтобы импортировать файл.",
    uploadFromDevice = "Загрузить с устройства", pasteUrl = "Вставьте прямую ссылку для загрузки",
    download = "Скачать", deleteConfirmDesc = "Это удалит файл из текущей версии сервера.",
    enabled = "Включён", disabled = "Отключён",
    addPlugin = "Добавить плагин",
    pluginsTip = "Загружайте .jar-плагины для Bukkit/Spigot/Paper. Ищите на spigotmc.org.",
    noPluginsInstalled = "Плагины не установлены", tapToAddPlugin = "Нажмите 'Добавить плагин' для загрузки .jar",
    cancel = "Отмена", accept = "ПРИНЯТЬ", enable = "Включить", disable = "Отключить",
    noInternetConnection = "Нет подключения к интернету.",
    hubTabPlugins = "Плагины", hubTabMods = "Моды", hubTabResourcePacks = "Ресурспаки",
    hubSearchPlaceholder = "Искать %s онлайн...",
    hubModLoaderRequired = "Требуется загрузчик модов",
    hubModLoaderDesc = "Эта версия сервера не использует поддерживаемый загрузчик модов. Переключитесь на Fabric или Quilt.",
    hubAddingFile = "Добавление файла: %d%%", hubDownloading = "Загрузка: %d%%",
    hubSectionDownloaded = "Загруженное", hubSectionDownloadedDesc = "Управляйте тем, что хранится для этой версии сервера.",
    hubSectionDiscover = "Обзор онлайн", hubSectionDiscoverDesc = "Здесь показаны только онлайн-результаты. Совпадающие установленные отмечены.",
    hubTapToExpand = "Нажмите стрелку для развёртки",
    hubNoDownloaded = "Для этой версии ещё нет загруженных %s.",
    hubNoOnlineResults = "Онлайн %s не найдены по этому запросу.",
    hubLoadingOnline = "Загрузка онлайн-результатов...",
    hubRetry = "Повторить", hubAdd = "Добавить", hubInstall = "Установить",
    hubInstalling = "Установка...", hubInstalled = "Установлено",
    hubSupportedMod = "Поддерживаемый мод", hubUnsupported = "Не поддерживается",
    hubUploadFromDevice = "Загрузить с устройства", hubPasteUrl = "Вставьте прямую ссылку для загрузки",
    hubDownloadAction = "Скачать",
    hubDeleteTitle = "Удалить %s?", hubDeleteDesc = "Это навсегда удалит файл из этой версии сервера.",
    hubDeleteAction = "Удалить",
    hubSearchRetry = "Поиск кэшируется и ограничен по запросам. Попробуйте через момент.",
    hubDetailFile = "Файл", hubDetailVersion = "Версия", hubDetailSize = "Размер",
    hubDetailApply = "Применить", hubDetailApplyDesc = "Перезапустите сервер после изменения плагинов или паков.",
    hubDetailVersionNotProvided = "Не указано",
    hubDetailDownloads = "Загрузки", hubDetailSource = "Источник", hubDetailSlug = "Slug",
    hubDetailDescription = "Описание", hubDetailSupport = "Поддержка",
    hubCommunityListing = "Запись сообщества",
    hubEnabledStatus = "Включён", hubDisabledStatus = "Отключён",
    worldsSectionCurrentWorld = "ТЕКУЩИЙ МИР", worldsMbOnDisk = "%s МБ на диске",
    worldsBackingUp = "РЕЗЕРВНОЕ КОПИРОВАНИЕ...", worldsBackup = "БЭКАП", worldsReset = "СБРОС",
    worldsStopBeforeReset = "Остановите сервер перед сбросом мира.",
    worldsSectionSlots = "СЛОТЫ МИРА", worldsAdd = "ДОБАВИТЬ",
    worldsSlotHint = "Проведите влево для удаления. Активные миры можно удалить только при остановленном сервере.",
    worldsSectionImport = "ИМПОРТ ИЗМЕРЕНИЙ",
    worldsImportGuideTitle = "Руководство по импорту", worldsImportGuideDesc = "Нажмите для просмотра руководства.",
    worldsUploadOverworld = "Загрузить Обычный мир", worldsUploadNether = "Загрузить Незер", worldsUploadEnd = "Загрузить Энд",
    worldsOverworldSub = "Основной мир (%s)", worldsNetherSub = "Измерение Незер (%s_nether)", worldsEndSub = "Измерение Энд (%s_the_end)",
    worldsSectionBackupHistory = "ИСТОРИЯ БЭКАПОВ", worldsFiles = "%d файлов",
    worldsNoBackups = "Бэкапы не найдены", worldsStopToSwitch = "Остановите сервер для смены мира",
    worldsStopToUpload = "Остановите сервер для загрузки", worldsExtracted = "%d%% извлечено",
    worldsUpload = "ЗАГРУЗИТЬ", worldsActive = "АКТИВЕН", worldsDelete = "Удалить",
    worldsResetTitle = "⚠️ Сброс мира",
    worldsResetDesc = "Выберите что удалить. Плагины, моды, конфиги и server.properties будут сохранены.",
    worldsResetRowWorld = "Папки мира (world, world_nether, world_the_end)",
    worldsResetRowPlayers = "Данные игроков (playerdata, stats, advancements)",
    worldsResetRowDatapacks = "Датапаки", worldsResetRowLogs = "Логи",
    worldsResetPreserved = "Всегда сохраняется: plugins/, mods/, config/, server.properties.",
    worldsResetDeleteSelected = "УДАЛИТЬ ВЫБРАННОЕ", worldsCancel = "ОТМЕНА",
    worldsRestoreTitle = "Восстановить бэкап?",
    worldsRestoreDesc = "Будет восстановлено:\n- Миры и измерения\n- Плагины, моды, ресурспаки\n- Конфиги сервера\n\nТекущие файлы будут перезаписаны.\nСервер должен быть остановлен.",
    worldsRestoreAction = "ВОССТАНОВИТЬ",
    worldsDeleteBackupTitle = "Удалить бэкап?", worldsDeleteBackupDesc = "Удалить %s?",
    worldsDeleteAction = "УДАЛИТЬ",
    worldsDeleteWorldTitle = "Удалить мир?",
    worldsDeleteWorldActive = "Удалить %s? PocketCraft переключится на другой мир.",
    worldsDeleteWorldInactive = "Удалить %s? Мир будет удалён из хранилища.",
    worldsImportGuideSheetTitle = "Руководство по импорту",
    worldsImportGuideText1 = "Экспорты Aternos можно загрузить как 3 отдельных ZIP: Обычный мир, Незер и Энд.",
    worldsImportGuideText2 = "Большинство бэкапов включают все измерения в одном архиве.",
    worldsImportGuideClose = "ЗАКРЫТЬ",
    filesSectionCurrentWorld = "ТЕКУЩИЙ МИР", filesActiveFolder = "Активная папка • %s МБ",
    filesDeleteActiveWorld = "УДАЛИТЬ АКТИВНЫЙ МИР",
    filesAddAnotherWorld = "Добавьте другой мир перед удалением этого.",
    filesSectionSeed = "СИД МИРА", filesSeedRandom = "Случайный",
    filesSeedUsedFor = "Сид для генерации мира", filesSeedCopied = "Сид скопирован в буфер обмена.",
    filesSeedEdit = "ИЗМЕНИТЬ", filesSectionCore = "ЯДРО СЕРВЕРА",
    filesMinecraftJava = "Minecraft Java %s", filesSwitchOrUpgrade = "Сменить или обновить",
    filesChange = "ИЗМЕНИТЬ", filesSectionBackup = "БЭКАП И ОБСЛУЖИВАНИЕ",
    filesQuickBackup = "Быстрый бэкап", filesAdvanced = "Подробнее...",
    filesSeedDialogTitle = "Установить сид мира",
    filesSeedDialogDesc = "Введите сид или оставьте пустым для случайного.",
    filesSeedDialogLabel = "Сид мира (необязательно)", filesSeedDialogConfirm = "ПОДТВЕРДИТЬ", filesSeedDialogCancel = "ОТМЕНА",
    filesDeleteWorldTitle = "Удалить активный мир?",
    filesDeleteWorldDesc = "%s будет удалён навсегда, произойдёт переключение на другой мир.",
    filesDeleteAction = "УДАЛИТЬ", filesDeleteCancel = "ОТМЕНА"
)

val Chinese = AppStrings(
    tabHome = "首页", tabPlayers = "玩家", tabStorage = "存储", tabMods = "模组", tabSettings = "设置",
    startServer = "启动服务器", stopServer = "停止", restartServer = "重启",
    starting = "正在启动...", stopping = "正在停止...", restarting = "正在重启...",
    offline = "离线", online = "在线",
    yourServer = "您的服务器", hostedOn = "由PocketCraft托管",
    tapToSwap = "点击切换世界或编辑详情",
    stopToSwitch = "停止服务器以切换世界",
    tapToChangeVersion = "点击更改版本", upgrade = "升级",
    ramAllocation = "内存分配", ramLow = "低", ramManual = "手动", ramFull = "全量",
    ramHighPerf = "高性能预设 — 可能导致过热",
    ramLowPerf = "低性能预设 — 省电", ramManualHint = "自定义内存分配",
    console = "控制台", clearLog = "清除", sendCommand = "发送命令",
    players = "玩家", tabOnline = "在线", tabAllPlayers = "所有玩家",
    tabWhitelist = "白名单", tabOps = "管理员", tabBanned = "封禁列表",
    kick = "踢出", ban = "封禁", makeOp = "设为OP", removeOp = "取消OP",
    unban = "解除封禁", addPlayer = "添加玩家",
    worlds = "世界", files = "文件", share = "分享", delete = "删除",
    view = "查看", close = "关闭", folder = "文件夹",
    uploading = "上传中...", chooseAction = "选择操作", unableToOpen = "无法打开文件。",
    settingsServer = "服务器", settingsApp = "应用", settingsAbout = "关于",
    performance = "性能与优化", worldSettings = "世界设置",
    networking = "网络", appPreferences = "应用偏好",
    sectionDeviceStorage = "设备存储", sectionAbout = "关于",
    viewDistance = "视距", viewDistanceDesc = "区块加载距离",
    viewDistanceHint = "低端设备建议使用较低值",
    simulationDistance = "模拟距离", simulationDistanceDesc = "生物/作物的刻更新距离",
    maxPowerMode = "最大性能模式", maxPowerModeDesc = "使用全部内存和最大渲染距离。可能导致过热。",
    mobSpawning = "生物生成优化", mobSpawningDesc = "减少实体数量以提升性能",
    mobSpawningStandard = "标准（原版）",
    difficulty = "难度", gamemode = "游戏模式", whitelist = "白名单",
    maxPlayers = "最大玩家数", broadcastConsole = "向管理员广播控制台",
    onlineMode = "正版验证", autoRestart = "自动重启",
    autoRestartDesc = "崩溃后自动重启服务器",
    forceExternalJvm = "强制外部JVM", forceExternalJvmDesc = "使用外部JVM而非内置JVM",
    configEditor = "高级配置编辑器", configEditorDesc = "直接编辑server.properties",
    openFolder = "打开服务器文件夹", openFolderDesc = "在文件管理器中浏览服务器文件",
    legalCenter = "法律中心", legalCenterDesc = "隐私政策与许可证",
    unsavedChanges = "未保存的更改", failedToSave = "保存失败",
    retry = "重试", save = "保存", saving = "保存中...", saved = "已保存",
    appLanguage = "应用语言", chooseLanguage = "选择您的首选语言",
    setWorldSeed = "设置世界种子", worldSeedLabel = "世界种子（可选）",
    downloaded = "已下载", managePluginsDesc = "管理已安装的插件和资源包",
    add = "添加", mods = "模组", resourcePacks = "资源包",
    noModsInstalled = "尚未安装模组", noResourcePacksInstalled = "尚未安装资源包",
    useAddButton = "使用添加按钮导入文件，或从发现页面安装。",
    uploadFromDevice = "从设备上传", pasteUrl = "粘贴直接下载链接",
    download = "下载", deleteConfirmDesc = "这将从当前服务器版本中删除该文件。",
    enabled = "已启用", disabled = "已禁用",
    addPlugin = "添加插件",
    pluginsTip = "上传Bukkit/Spigot/Paper兼容的.jar插件。在spigotmc.org查找插件。",
    noPluginsInstalled = "未安装插件", tapToAddPlugin = "点击'添加插件'上传.jar文件",
    cancel = "取消", accept = "接受", enable = "启用", disable = "禁用",
    noInternetConnection = "无网络连接，请检查您的网络。",
    hubTabPlugins = "插件", hubTabMods = "模组", hubTabResourcePacks = "资源包",
    hubSearchPlaceholder = "搜索在线%s...",
    hubModLoaderRequired = "模组需要模组加载器",
    hubModLoaderDesc = "此服务器版本未使用受支持的模组加载器。请切换到Fabric或Quilt。",
    hubAddingFile = "添加文件: %d%%", hubDownloading = "下载中: %d%%",
    hubSectionDownloaded = "已下载", hubSectionDownloadedDesc = "管理已为此服务器版本存储的内容。",
    hubSectionDiscover = "在线发现", hubSectionDiscoverDesc = "这里只显示在线结果。已安装的匹配项已标记。",
    hubTapToExpand = "点击箭头展开",
    hubNoDownloaded = "此版本尚无已下载的%s。",
    hubNoOnlineResults = "此搜索未匹配到在线%s。",
    hubLoadingOnline = "正在加载在线结果...",
    hubRetry = "重试", hubAdd = "添加", hubInstall = "安装",
    hubInstalling = "安装中...", hubInstalled = "已安装",
    hubSupportedMod = "受支持模组", hubUnsupported = "不受支持",
    hubUploadFromDevice = "从设备上传", hubPasteUrl = "粘贴直接下载链接",
    hubDownloadAction = "下载",
    hubDeleteTitle = "删除%s？", hubDeleteDesc = "这将永久从此服务器版本中删除该文件。",
    hubDeleteAction = "删除",
    hubSearchRetry = "搜索已缓存且有频率限制，稍后重试通常有效。",
    hubDetailFile = "文件", hubDetailVersion = "版本", hubDetailSize = "大小",
    hubDetailApply = "应用", hubDetailApplyDesc = "更改插件或资源包后重启服务器。",
    hubDetailVersionNotProvided = "未提供",
    hubDetailDownloads = "下载量", hubDetailSource = "来源", hubDetailSlug = "标识",
    hubDetailDescription = "描述", hubDetailSupport = "支持",
    hubCommunityListing = "社区条目",
    hubEnabledStatus = "已启用", hubDisabledStatus = "已禁用",
    worldsSectionCurrentWorld = "当前世界", worldsMbOnDisk = "%s MB（磁盘）",
    worldsBackingUp = "备份中...", worldsBackup = "备份", worldsReset = "重置",
    worldsStopBeforeReset = "重置世界前请先停止服务器。",
    worldsSectionSlots = "世界槽位", worldsAdd = "添加",
    worldsSlotHint = "向左滑动删除。只有服务器停止时才能删除活跃世界。",
    worldsSectionImport = "导入维度",
    worldsImportGuideTitle = "导入指南", worldsImportGuideDesc = "点击查看世界和维度导入说明。",
    worldsUploadOverworld = "上传主世界", worldsUploadNether = "上传下界", worldsUploadEnd = "上传末地",
    worldsOverworldSub = "主世界 (%s)", worldsNetherSub = "下界维度 (%s_nether)", worldsEndSub = "末地维度 (%s_the_end)",
    worldsSectionBackupHistory = "备份历史", worldsFiles = "%d 个文件",
    worldsNoBackups = "未找到备份", worldsStopToSwitch = "停止服务器以切换世界",
    worldsStopToUpload = "停止服务器以上传", worldsExtracted = "已解压 %d%%",
    worldsUpload = "上传", worldsActive = "活跃", worldsDelete = "删除",
    worldsResetTitle = "⚠️ 重置世界",
    worldsResetDesc = "选择要删除的内容。插件、模组、配置和server.properties将被保留。",
    worldsResetRowWorld = "世界文件夹 (world, world_nether, world_the_end)",
    worldsResetRowPlayers = "玩家数据 (playerdata, stats, advancements)",
    worldsResetRowDatapacks = "数据包", worldsResetRowLogs = "日志",
    worldsResetPreserved = "始终保留：plugins/、mods/、config/、server.properties。",
    worldsResetDeleteSelected = "删除所选", worldsCancel = "取消",
    worldsRestoreTitle = "恢复备份？",
    worldsRestoreDesc = "将恢复：\n- 世界和维度数据\n- 插件、模组和资源包\n- 服务器配置\n\n当前文件将被覆盖。\n请确保服务器已停止。",
    worldsRestoreAction = "恢复",
    worldsDeleteBackupTitle = "删除备份？", worldsDeleteBackupDesc = "确定删除 %s？",
    worldsDeleteAction = "删除",
    worldsDeleteWorldTitle = "删除世界？",
    worldsDeleteWorldActive = "删除 %s？PocketCraft 将切换到另一个世界。",
    worldsDeleteWorldInactive = "删除 %s？该世界将从存储中移除。",
    worldsImportGuideSheetTitle = "导入指南",
    worldsImportGuideText1 = "Aternos 导出可以作为 3 个独立的 ZIP 上传：主世界、下界和末地。",
    worldsImportGuideText2 = "大多数世界备份已将所有维度包含在一个存档中，导入一次即可。",
    worldsImportGuideClose = "关闭",
    filesSectionCurrentWorld = "当前世界", filesActiveFolder = "活跃文件夹 • %s MB",
    filesDeleteActiveWorld = "删除活跃世界",
    filesAddAnotherWorld = "删除此世界前请先添加另一个世界。",
    filesSectionSeed = "世界种子", filesSeedRandom = "随机",
    filesSeedUsedFor = "用于世界生成的种子", filesSeedCopied = "种子已复制到剪贴板。",
    filesSeedEdit = "编辑", filesSectionCore = "服务端核心",
    filesMinecraftJava = "Minecraft Java %s", filesSwitchOrUpgrade = "切换或升级",
    filesChange = "更改", filesSectionBackup = "备份与维护",
    filesQuickBackup = "快速备份", filesAdvanced = "高级...",
    filesSeedDialogTitle = "设置世界种子",
    filesSeedDialogDesc = "输入种子，留空则随机生成。",
    filesSeedDialogLabel = "世界种子（可选）", filesSeedDialogConfirm = "确认", filesSeedDialogCancel = "取消",
    filesDeleteWorldTitle = "删除活跃世界？",
    filesDeleteWorldDesc = "将永久删除 %s 并切换到另一个已保存的世界。",
    filesDeleteAction = "删除", filesDeleteCancel = "取消"
)

fun appStringsFor(lang: String): AppStrings = when (lang) {
    "de" -> German
    "es" -> Spanish
    "ru" -> Russian
    "zh" -> Chinese
    else -> AppStrings()
}

val LocalAppStrings = compositionLocalOf { AppStrings() }
